# Generated by Django 4.2.15 on 2024-08-30 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Псевдоним')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('note', models.TextField(default='Описание оборудования', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_matrix', models.IntegerField(default=800, validators=[django.core.validators.MinValueValidator(240)], verbose_name='Ширина матрицы')),
                ('h_matrix', models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(240)], verbose_name='Высота матрицы')),
            ],
            options={
                'verbose_name': 'Матрица камеры',
                'verbose_name_plural': 'Матрицы камеры',
                'unique_together': {('w_matrix', 'h_matrix')},
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Псевдоним')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('n_rotors', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество моторов')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera', to='drone.camera', verbose_name='Камера(ы)')),
                ('equipment', models.ManyToManyField(blank=True, related_name='equipment', to='drone.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Дрон',
                'verbose_name_plural': 'Дроны',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='matrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix', to='drone.matrix', verbose_name='Матрица'),
        ),
    ]
