# Generated by Django 4.2.15 on 2024-08-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='api',
            field=models.CharField(max_length=30, null=True, verbose_name='API-интерфейс'),
        ),
    ]
