# Generated by Django 4.2.15 on 2024-08-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_drone_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='api',
        ),
        migrations.AddField(
            model_name='drone',
            name='api_type',
            field=models.CharField(choices=[('A', 'airsim'), ('M', 'mavlink'), ('D', 'dji')], default='A', max_length=1, verbose_name='Тип API-интерфейса'),
        ),
    ]
